[workspace]
members = [
  "zomes/profiles",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "develop", package = "hc_utils"}
hdk3 = {git = "https://github.com/holochain/holochain", rev = "5daac31fe21f5d10c192bbe208f0b11f8ee67d88", package = "hdk3"}
holo_hash = {git = "https://github.com/holochain/holochain", rev = "5daac31fe21f5d10c192bbe208f0b11f8ee67d88", package = "holo_hash"}
